name: React CI Pipeline

on:
  # 1. Run when push to main or develop branch
  push:
    branches:
      - "main"
      - "develop"

  # 2. Run when open pull request to main or develop branch
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Run Unit Tests
        run: npx vitest run

      - name: Build Project
        run: pnpm run build
